# Generated by Django 4.0.6 on 2022-09-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_category_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='sub_category_id',
        ),
        migrations.AddField(
            model_name='sub_category',
            name='cat_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.category'),
        ),
    ]
