# Generated by Django 4.0.6 on 2022-09-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_brands_cat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='size_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.TextField(max_length=100)),
            ],
        ),
    ]
