# Generated by Django 4.0.6 on 2022-09-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_size_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(default='', max_length=100)),
                ('image', models.FileField(default='', upload_to='media/')),
                ('price', models.CharField(default='', max_length=100)),
                ('qty', models.CharField(default='', max_length=100)),
                ('cat_id', models.CharField(default='', max_length=100)),
                ('sub_cat', models.CharField(default='', max_length=100)),
                ('brand_id', models.CharField(default='', max_length=100)),
                ('size_id', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
