# Generated by Django 4.0.6 on 2022-09-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_new_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='change_pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('newpassword', models.CharField(max_length=100)),
                ('conformpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
