# Generated by Django 4.0.6 on 2022-09-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_add_to_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='user_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
