# Generated by Django 4.0.6 on 2022-09-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_add_to_cart_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='color_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
            ],
        ),
    ]
