# Generated by Django 4.0.6 on 2022-09-27 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_color_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_cart',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.product_master'),
        ),
    ]
