# Generated by Django 4.0.6 on 2022-09-27 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_add_to_cart_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_cart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.new_register'),
        ),
    ]
