# Generated by Django 4.0.6 on 2022-11-08 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_add_to_cart_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_master',
            name='brand_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.brands'),
        ),
        migrations.AlterField(
            model_name='product_master',
            name='cat_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.category'),
        ),
        migrations.AlterField(
            model_name='product_master',
            name='size_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.size_master'),
        ),
        migrations.AlterField(
            model_name='product_master',
            name='sub_cat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.sub_category'),
        ),
    ]
