# Generated by Django 4.0.6 on 2022-11-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_chackout_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='chackout_register',
            name='cart_ids',
            field=models.CharField(default='[]', max_length=500),
        ),
    ]
