# Generated by Django 4.1.3 on 2022-11-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_chackout_register_cart_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='chackout_register',
            name='pay_status',
            field=models.CharField(default='unpaid', max_length=50),
        ),
    ]
