# Generated by Django 4.1.3 on 2022-11-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_chackout_register_pay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chackout_register',
            name='Amount',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
